# Generated by Django 2.2.3 on 2020-04-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackI', '0002_auto_20200423_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='token_team',
            new_name='token',
        ),
    ]
