# Generated by Django 2.2.3 on 2020-04-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackI', '0004_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Channel'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token'},
        ),
    ]
